name: 'Set Version'
description: 'Increments version and outputs tag and skip'
inputs:
  tracker:
    description: 'Path to version tracker'
    required: false
    default: version.json

outputs:
  tag:
    description: 'The version tag'
    value: ${{ steps.extract.outputs.tag }}
  skip:
    description: 'Whether to skip the version step'
    value: ${{ steps.extract.outputs.skip }}

runs:
  using: 'composite'
  steps:
    - name: Run version script
      shell: bash
      run: |
        chmod +x ${{ github.action_path }}/entrypoint.sh
        ${{ github.action_path }}/entrypoint.sh "${{ inputs.tracker }}"

    - name: Extract outputs
      id: extract
      shell: bash
      run: |
        echo "tag=$(cat tag.txt)" >> "$GITHUB_OUTPUT"
        echo "skip=$(cat skip.txt)" >> "$GITHUB_OUTPUT"
