name: 'Set Version'
description: 'Tags the repo with an incremented version number if the latest commit has changed'
author: 'Adam Oneil'
inputs:
  filename:
    description: 'Path to version tracker file (JSON)'
    required: false
    default: 'version.json'

outputs:
  tag:
    description: 'The tag that was applied (if any)'
  skip:
    description: 'true if no tag was applied'

runs:
  using: 'composite'
  steps:
    - name: Run tagger
      shell: bash
      run: |
        chmod +x ${{ github.action_path }}/entrypoint.sh
        ${{ github.action_path }}/entrypoint.sh "${{ inputs.filename }}"
